// <auto-generated />
using System;
using BuckeyeMarketplace.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuckeyeMarketplace.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331191722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("BuckeyeMarketplace.API.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BuckeyeMarketplace.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Textbooks",
                            Description = "Used calculus textbook in good condition. Includes some notes but all pages intact.",
                            ImageUrl = "https://picsum.photos/300/400?random=1",
                            PostedDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 65.00m,
                            SellerName = "Sarah Chen",
                            Title = "Calculus II Textbook (Larson, 11th Ed)"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Textbooks",
                            Description = "New condition, still in original packaging. Required for PSYCH 101.",
                            ImageUrl = "https://picsum.photos/300/400?random=2",
                            PostedDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 95.50m,
                            SellerName = "Marcus Johnson",
                            Title = "Intro to Psychology 101 - Required Textbook"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Textbooks",
                            Description = "Good condition with minimal highlighting. Includes access code not used.",
                            ImageUrl = "https://picsum.photos/300/400?random=3",
                            PostedDate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 75.99m,
                            SellerName = "Emma Rodriguez",
                            Title = "Microeconomics: Principles & Applications Textbook"
                        },
                        new
                        {
                            Id = 4,
                            Category = "OSU Clothing",
                            Description = "Authentic Ohio State hoodie. Worn a few times, excellent condition. Classic scarlet color.",
                            ImageUrl = "https://picsum.photos/300/400?random=4",
                            PostedDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 45.00m,
                            SellerName = "Alex Kim",
                            Title = "Official OSU Scarlet & Gray Hoodie - Size L"
                        },
                        new
                        {
                            Id = 5,
                            Category = "OSU Clothing",
                            Description = "Adjustable cap with embroidered logo. Perfect condition, barely worn.",
                            ImageUrl = "https://picsum.photos/300/400?random=5",
                            PostedDate = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 18.50m,
                            SellerName = "Jordan Lee",
                            Title = "OSU Buckeyes Baseball Cap - Gray"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            Description = "Works perfectly. Includes original case and charging cable. Used for engineering courses.",
                            ImageUrl = "https://picsum.photos/300/400?random=6",
                            PostedDate = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 85.00m,
                            SellerName = "Priya Patel",
                            Title = "TI-84 Plus Graphing Calculator"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Fan Gear",
                            Description = "Official replica jersey, worn once, like new. Perfect for game day or tailgate.",
                            ImageUrl = "https://picsum.photos/300/400?random=7",
                            PostedDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 55.00m,
                            SellerName = "Tyler Brooks",
                            Title = "OSU Football Game Jersey - Treveyon #5"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Fan Gear",
                            Description = "Commemorative challenge coin with Brutus Buckeye. Great collectible for any student.",
                            ImageUrl = "https://picsum.photos/300/400?random=8",
                            PostedDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 12.99m,
                            SellerName = "Casey Williams",
                            Title = "OSU Alumni Challenge Coin"
                        });
                });

            modelBuilder.Entity("BuckeyeMarketplace.API.Models.CartItem", b =>
                {
                    b.HasOne("BuckeyeMarketplace.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
